// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvllAirehV9oQQklQcAvt1lM5QM2U2pg8',
    appId: '1:960358110550:web:a705340866f8d3ecebf2f7',
    messagingSenderId: '960358110550',
    projectId: 'havera-ex',
    authDomain: 'havera-ex.firebaseapp.com',
    storageBucket: 'havera-ex.firebasestorage.app',
    measurementId: 'G-FTMV1404YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOz15JqvEjUCHruMXPCdgntlZ9de8TWMg',
    appId: '1:960358110550:android:cd7f5c7d81476238ebf2f7',
    messagingSenderId: '960358110550',
    projectId: 'havera-ex',
    storageBucket: 'havera-ex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTECQH4QBZUAeYId0T0dLvSwYwlck55G0',
    appId: '1:960358110550:ios:6edd07f9ad932b27ebf2f7',
    messagingSenderId: '960358110550',
    projectId: 'havera-ex',
    storageBucket: 'havera-ex.firebasestorage.app',
    iosBundleId: 'com.example.flutterEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTECQH4QBZUAeYId0T0dLvSwYwlck55G0',
    appId: '1:960358110550:ios:6edd07f9ad932b27ebf2f7',
    messagingSenderId: '960358110550',
    projectId: 'havera-ex',
    storageBucket: 'havera-ex.firebasestorage.app',
    iosBundleId: 'com.example.flutterEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvllAirehV9oQQklQcAvt1lM5QM2U2pg8',
    appId: '1:960358110550:web:5378deef95d74e2aebf2f7',
    messagingSenderId: '960358110550',
    projectId: 'havera-ex',
    authDomain: 'havera-ex.firebaseapp.com',
    storageBucket: 'havera-ex.firebasestorage.app',
    measurementId: 'G-G4KDSK95ZB',
  );
}
